services:
  # Backend Service
  - type: web
    name: mgnrega-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    healthCheckPath: /api/health

  # Frontend Service
  - type: web
    name: mgnrega-frontend
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: mgnrega-backend
          envVarKey: RENDER_EXTERNAL_URL
